query AllEvaluatedArticles($sentiment: String) {
  allEvaluatedArticles(filter: { aiSentiment: { eq: $sentiment } }, orderBy: [publishedDatetime_DESC]) {
    ...EvaluatedArticle
  }
}

fragment EvaluatedArticle on EvaluatedArticleRecord {
  id
  title
  description
  link
  publishedDatetime
  formattedDatetime
  publication {
    id
    organization
  }
  aiSentiment
  aiComment
}

fragment ArticleListBlock on ArticleListBlockRecord {
  id
}
