query Publication {
  allPublications {
    organization
    rssLink
    enabled
  }
}

query AiPrompt {
  aiPrompt {
    system
    user
  }
}

query PageSlug {
  allPages {
    slug
  }
}

query Page($slug: String!) {
  page(filter: { slug: { eq: $slug } }) {
    id
    slug
    title
  }
}
