query Page {
  allPages {
    ...Page
  }
}

query Publication {
  allPublications {
    ...Publication
  }
}

query Prompt {
  prompt {
    ...Prompt
  }
}

query Site {
  _site {
    globalSeo {
      siteName
      titleSuffix
      fallbackSeo {
        title
        description
      }
    }
  }
}

fragment Page on PageRecord {
  navigationLabel
  slug
  hidden
  content {
    value
    blocks {
      __typename
      ...ArticleListBlock
      ...PublicationLogoBlock
    }
  }
  seo {
    title
    description
  }
}

fragment Publication on PublicationRecord {
  id
  organization
  rssLink
  enabled
  logo {
    responsiveImage(imgixParams: { auto: format, h: 33 }) {
      ...ResponsiveImage
    }
  }
}

fragment Prompt on PromptRecord {
  system
  user
}

fragment ResponsiveImage on ResponsiveImage {
  srcSet
  webpSrcSet
  sizes
  src
  width
  height
  aspectRatio
  alt
  title
  base64
}
